### ISSUE TITLE
WithField with a Map inside fails JSON round-trip

### ISSUE THREAD

**Issue by koterpillar** [NCrashed/aeson-injector#1]
```haskell
import qualified Data.Map as Map

roundtrip :: (FromJSON a, ToJSON a) => a -> Either String a
roundtrip = parseEither parseJSON . toJSON

testvalue :: WithField "foo" Int (Map.Map Bool Int)
testvalue = WithField 10 (Map.fromList [(True, 20), (False, 30)])
```

Expected result: `roundtrip testvalue == Right testvalue`

Actual result:

```haskell
> roundtrip testvalue
Left "Error in $: key \"value\" not present"
```

`WithField` injects `foo` into the JSON object, but fails to take it off during _parsing_ before passing the value to the inner type. `Map` fails to parse `foo` as a boolean, so `WithFields` tries the wrapper case, but that also fails with the error message shown.

A fix would remove the injected field from the JSON object before calling `parseJSON` on the inner type here: https://github.com/NCrashed/aeson-injector/blob/master/src/Data/Aeson/WithField.hs#L246

**Comment by NCrashed** [comment]
Thank you for report! Reopen, please, if the problem remains.
